name: Review

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  lint-actions:
    name: Lint GitHub Actions

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Prettier
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm --global install prettier

      - name: Lint workflow code
        run: prettier --check .github

  lint-docs:
    name: Lint Docs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Prettier
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm --global install prettier

      - name: Lint markdown
        run: prettier --check **.md

  lint-iac:
    name: Lint IaC

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Lint Terraform code
        run: terraform fmt -recursive -check
        working-directory: ./src

  validate-iac:
    name: Validate IaC

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Validate Terraform code
        run: terraform validate
        working-directory: ./src
